# Generated by Django 4.1.6 on 2023-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='donate',
            field=models.FloatField(default=0),
        ),
    ]
